services:
  - type: web
    name: leisure-crm
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: leisure-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
